// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: clutch/v1/say_hi.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayHiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Greet         string                 `protobuf:"bytes,1,opt,name=greet,proto3" json:"greet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHiRequest) Reset() {
	*x = SayHiRequest{}
	mi := &file_clutch_v1_say_hi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHiRequest) ProtoMessage() {}

func (x *SayHiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clutch_v1_say_hi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHiRequest.ProtoReflect.Descriptor instead.
func (*SayHiRequest) Descriptor() ([]byte, []int) {
	return file_clutch_v1_say_hi_proto_rawDescGZIP(), []int{0}
}

func (x *SayHiRequest) GetGreet() string {
	if x != nil {
		return x.Greet
	}
	return ""
}

type SayHiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Greet         string                 `protobuf:"bytes,1,opt,name=greet,proto3" json:"greet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHiResponse) Reset() {
	*x = SayHiResponse{}
	mi := &file_clutch_v1_say_hi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHiResponse) ProtoMessage() {}

func (x *SayHiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clutch_v1_say_hi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHiResponse.ProtoReflect.Descriptor instead.
func (*SayHiResponse) Descriptor() ([]byte, []int) {
	return file_clutch_v1_say_hi_proto_rawDescGZIP(), []int{1}
}

func (x *SayHiResponse) GetGreet() string {
	if x != nil {
		return x.Greet
	}
	return ""
}

var File_clutch_v1_say_hi_proto protoreflect.FileDescriptor

const file_clutch_v1_say_hi_proto_rawDesc = "" +
	"\n" +
	"\x16clutch/v1/say_hi.proto\x12\rclutch_rpc.v1\"$\n" +
	"\fSayHiRequest\x12\x14\n" +
	"\x05greet\x18\x01 \x01(\tR\x05greet\"%\n" +
	"\rSayHiResponse\x12\x14\n" +
	"\x05greet\x18\x01 \x01(\tR\x05greet2T\n" +
	"\fSayHiService\x12D\n" +
	"\x05SayHi\x12\x1b.clutch_rpc.v1.SayHiRequest\x1a\x1c.clutch_rpc.v1.SayHiResponse\"\x00B-Z+github.com/vinewz/clutchRPC/go/pb/clutch/v1b\x06proto3"

var (
	file_clutch_v1_say_hi_proto_rawDescOnce sync.Once
	file_clutch_v1_say_hi_proto_rawDescData []byte
)

func file_clutch_v1_say_hi_proto_rawDescGZIP() []byte {
	file_clutch_v1_say_hi_proto_rawDescOnce.Do(func() {
		file_clutch_v1_say_hi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clutch_v1_say_hi_proto_rawDesc), len(file_clutch_v1_say_hi_proto_rawDesc)))
	})
	return file_clutch_v1_say_hi_proto_rawDescData
}

var file_clutch_v1_say_hi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_clutch_v1_say_hi_proto_goTypes = []any{
	(*SayHiRequest)(nil),  // 0: clutch_rpc.v1.SayHiRequest
	(*SayHiResponse)(nil), // 1: clutch_rpc.v1.SayHiResponse
}
var file_clutch_v1_say_hi_proto_depIdxs = []int32{
	0, // 0: clutch_rpc.v1.SayHiService.SayHi:input_type -> clutch_rpc.v1.SayHiRequest
	1, // 1: clutch_rpc.v1.SayHiService.SayHi:output_type -> clutch_rpc.v1.SayHiResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clutch_v1_say_hi_proto_init() }
func file_clutch_v1_say_hi_proto_init() {
	if File_clutch_v1_say_hi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clutch_v1_say_hi_proto_rawDesc), len(file_clutch_v1_say_hi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clutch_v1_say_hi_proto_goTypes,
		DependencyIndexes: file_clutch_v1_say_hi_proto_depIdxs,
		MessageInfos:      file_clutch_v1_say_hi_proto_msgTypes,
	}.Build()
	File_clutch_v1_say_hi_proto = out.File
	file_clutch_v1_say_hi_proto_goTypes = nil
	file_clutch_v1_say_hi_proto_depIdxs = nil
}
