// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: clutch/v1/toggle_window.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ToggleWindowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleWindowRequest) Reset() {
	*x = ToggleWindowRequest{}
	mi := &file_clutch_v1_toggle_window_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleWindowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleWindowRequest) ProtoMessage() {}

func (x *ToggleWindowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clutch_v1_toggle_window_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleWindowRequest.ProtoReflect.Descriptor instead.
func (*ToggleWindowRequest) Descriptor() ([]byte, []int) {
	return file_clutch_v1_toggle_window_proto_rawDescGZIP(), []int{0}
}

type ToggleWindowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleWindowResponse) Reset() {
	*x = ToggleWindowResponse{}
	mi := &file_clutch_v1_toggle_window_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleWindowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleWindowResponse) ProtoMessage() {}

func (x *ToggleWindowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clutch_v1_toggle_window_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleWindowResponse.ProtoReflect.Descriptor instead.
func (*ToggleWindowResponse) Descriptor() ([]byte, []int) {
	return file_clutch_v1_toggle_window_proto_rawDescGZIP(), []int{1}
}

var File_clutch_v1_toggle_window_proto protoreflect.FileDescriptor

const file_clutch_v1_toggle_window_proto_rawDesc = "" +
	"\n" +
	"\x1dclutch/v1/toggle_window.proto\x12\rclutch_rpc.v1\"\x15\n" +
	"\x13ToggleWindowRequest\"\x16\n" +
	"\x14ToggleWindowResponse2p\n" +
	"\x13ToggleWindowService\x12Y\n" +
	"\fToggleWindow\x12\".clutch_rpc.v1.ToggleWindowRequest\x1a#.clutch_rpc.v1.ToggleWindowResponse\"\x00B-Z+github.com/vinewz/clutchRPC/go/pb/clutch/v1b\x06proto3"

var (
	file_clutch_v1_toggle_window_proto_rawDescOnce sync.Once
	file_clutch_v1_toggle_window_proto_rawDescData []byte
)

func file_clutch_v1_toggle_window_proto_rawDescGZIP() []byte {
	file_clutch_v1_toggle_window_proto_rawDescOnce.Do(func() {
		file_clutch_v1_toggle_window_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clutch_v1_toggle_window_proto_rawDesc), len(file_clutch_v1_toggle_window_proto_rawDesc)))
	})
	return file_clutch_v1_toggle_window_proto_rawDescData
}

var file_clutch_v1_toggle_window_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_clutch_v1_toggle_window_proto_goTypes = []any{
	(*ToggleWindowRequest)(nil),  // 0: clutch_rpc.v1.ToggleWindowRequest
	(*ToggleWindowResponse)(nil), // 1: clutch_rpc.v1.ToggleWindowResponse
}
var file_clutch_v1_toggle_window_proto_depIdxs = []int32{
	0, // 0: clutch_rpc.v1.ToggleWindowService.ToggleWindow:input_type -> clutch_rpc.v1.ToggleWindowRequest
	1, // 1: clutch_rpc.v1.ToggleWindowService.ToggleWindow:output_type -> clutch_rpc.v1.ToggleWindowResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clutch_v1_toggle_window_proto_init() }
func file_clutch_v1_toggle_window_proto_init() {
	if File_clutch_v1_toggle_window_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clutch_v1_toggle_window_proto_rawDesc), len(file_clutch_v1_toggle_window_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clutch_v1_toggle_window_proto_goTypes,
		DependencyIndexes: file_clutch_v1_toggle_window_proto_depIdxs,
		MessageInfos:      file_clutch_v1_toggle_window_proto_msgTypes,
	}.Build()
	File_clutch_v1_toggle_window_proto = out.File
	file_clutch_v1_toggle_window_proto_goTypes = nil
	file_clutch_v1_toggle_window_proto_depIdxs = nil
}
